version: '2'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: "enginedb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    expose:
      - "5432"
    ports:
      - "54321:5432"

  server:
    build: ./matching-engine
    user: root
    volumes:
      - ./matching-engine:/code
    command: bash -c "./run.sh"
    ports:
      - "12345:12345"
    expose:
      - "12345"
    depends_on:
      - db
