# Generated by Django 4.2.11 on 2024-04-26 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('go to warehouse', 'Go to Warehouse'), ('arrive at warehouse', 'Arrive at Warehouse'), ('delivering', 'Delivering')], max_length=50)),
                ('current_x', models.IntegerField()),
                ('current_y', models.IntegerField()),
                ('ready_to_pickup_time', models.DateTimeField(blank=True, null=True)),
                ('arrive_warehouse_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_start_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('tracking_number', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('at warehouse', 'At Warehouse'), ('loading', 'Loading'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], max_length=50)),
                ('whats_inside', models.CharField(max_length=255)),
                ('package_id_from_amazon', models.BigIntegerField(null=True, unique=True)),
                ('whid', models.IntegerField(blank=True, null=True)),
                ('amazon_id', models.CharField(blank=True, max_length=255, null=True)),
                ('dest_addr_x', models.IntegerField(blank=True, null=True)),
                ('dest_addr_y', models.IntegerField(blank=True, null=True)),
                ('init_addr_x', models.IntegerField(blank=True, null=True)),
                ('init_addr_y', models.IntegerField(blank=True, null=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UPS.truck')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=255, null=True)),
                ('go_warehouse_time', models.DateTimeField(blank=True, null=True)),
                ('arrive_warehouse_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_start_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPS.package')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPS.truck')),
            ],
        ),
    ]
