# Generated by Django 4.2.10 on 2024-04-24 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0002_rename_idle_x_truck_current_x_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='Amazon_id',
            new_name='amazon_id',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='desAddr_x',
            new_name='dest_addr_x',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='desAddr_y',
            new_name='dest_addr_y',
        ),
    ]
