# Generated by Django 4.2.10 on 2024-04-24 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UPS', '0003_rename_amazon_id_package_amazon_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery',
            old_name='arriveWarehouse_time',
            new_name='arrive_warehouse_time',
        ),
        migrations.RenameField(
            model_name='delivery',
            old_name='goWarehouse_time',
            new_name='go_warehouse_time',
        ),
    ]
