# Generated by Django 5.0.2 on 2024-02-07 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('rider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_active_driver', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(max_length=255)),
                ('vehicle_license_plate_number', models.CharField(max_length=255)),
                ('special_vehicle_info', models.TextField(blank=True, null=True)),
                ('vehicle_capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('myUber.rider',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('destination_address', models.CharField(max_length=255)),
                ('required_arrival_date', models.DateField()),
                ('required_arrival_time', models.TimeField()),
                ('total_passengers', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=255, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('shareable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='open', max_length=10)),
                ('ride_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_orders', to=settings.AUTH_USER_MODEL)),
                ('riders', models.ManyToManyField(related_name='joined_orders', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='myUber.driver')),
            ],
        ),
        migrations.CreateModel(
            name='RideParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField(default=1, help_text="Number of passengers in the rider's party")),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='myUber.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
