# Generated by Django 4.2.9 on 2024-02-04 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('rider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myUber.rider')),
                ('is_active_driver', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('vehicle_type', models.CharField(max_length=64)),
                ('vehicle_license_plate_number', models.CharField(max_length=32)),
                ('special_vehicle_info', models.TextField(blank=True, null=True)),
                ('vehicle_capacity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('myUber.rider',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, unique=True)),
                ('destination_address', models.CharField(max_length=255)),
                ('required_arrival_date', models.DateField()),
                ('required_arrival_time', models.TimeField()),
                ('total_passengers', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, max_length=64, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('shareable', models.BooleanField(default=False)),
                ('is_open', models.BooleanField(default=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ride_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_orders', to='myUber.rider')),
                ('riders', models.ManyToManyField(related_name='joined_orders', to='myUber.rider')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_orders', to='myUber.driver')),
            ],
        ),
    ]
