# Generated by Django 4.2.9 on 2024-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myUber', '0002_alter_driver_first_name_alter_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
