# Generated by Django 4.2.9 on 2024-02-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myUber', '0004_remove_order_is_confirmed_remove_order_is_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='fee',
        ),
    ]
