# Generated by Django 4.2.9 on 2024-02-06 23:27

from django.db import migrations, models
import uuid

def fix_order_numbers(apps, schema_editor):
    Order = apps.get_model('myUber', 'Order')
    for order in Order.objects.all():
        if not order.order_number:
            order.order_number = uuid.uuid4()
            order.save()



class Migration(migrations.Migration):

    dependencies = [
        ('myUber', '0005_remove_order_fee'),
    ]

    operations = [
        migrations.RunPython(fix_order_numbers),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
