# Generated by Django 4.2.10 on 2024-04-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('go to warehouse', 'Go to Warehouse'), ('arrive at warehouse', 'Arrive at Warehouse'), ('delivering', 'Delivering')], max_length=50)),
                ('idle_x', models.IntegerField()),
                ('idle_y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('package_id', models.AutoField(primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('at warehouse', 'At Warehouse'), ('delivering', 'Delivering'), ('delivered', 'Delivered')], max_length=50)),
                ('destination_address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UPS.user')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('delivery_id', models.AutoField(primary_key=True, serialize=False)),
                ('pickup_location', models.CharField(max_length=255)),
                ('goWarehouse_time', models.DateTimeField(blank=True, null=True)),
                ('arriveWarehouse_time', models.DateTimeField(blank=True, null=True)),
                ('delivery_start_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_time', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPS.package')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UPS.truck')),
            ],
        ),
    ]
